// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnM1FZIZgCq646Ahp_z2TPoSE4Dk7x8us',
    appId: '1:128638350868:web:12b2aa3bdb22dabed1d901',
    messagingSenderId: '128638350868',
    projectId: 'whatsappclone-2c6f0',
    authDomain: 'whatsappclone-2c6f0.firebaseapp.com',
    storageBucket: 'whatsappclone-2c6f0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8dw8UGBhG_0S4j3s9LEmagakdHjiLHFQ',
    appId: '1:128638350868:android:bd0276273617058cd1d901',
    messagingSenderId: '128638350868',
    projectId: 'whatsappclone-2c6f0',
    storageBucket: 'whatsappclone-2c6f0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXQqHm2QoXJ8milUud-VaT4_YYOKAbofI',
    appId: '1:128638350868:ios:efbc509c31819f0fd1d901',
    messagingSenderId: '128638350868',
    projectId: 'whatsappclone-2c6f0',
    storageBucket: 'whatsappclone-2c6f0.firebasestorage.app',
    iosBundleId: 'com.example.whatsappclone',
  );
}
